FROM node:22.17.0-alpine3.22 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY .env ./
COPY . .
RUN yarn build

FROM node:22.17.0-alpine3.22
WORKDIR /app
COPY package*.json ./
COPY .env ./
RUN npm install --production
COPY --from=builder /app/dist ./dist
CMD ["yarn", "start:prod"]