import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import { AuthContextProvider } from '@/contexts/auth.context';
import { ThemeProvider } from '@/provider/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'TaleNet',
    description: 'Generated by create next app',
    applicationName: 'TaleNet',
    generator: 'Next.js',
    keywords: ['TaleNet', 'Book', 'Network', 'Read Book', 'Write Book', 'Story', 'Love Book'],
    creator: 'Phan Kien',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' className='light' suppressHydrationWarning>
            <head />
            <body
                className={cn('min-h-screen w-full', inter.className, {
                    'debug-screens': process.env.NODE_ENV === 'development',
                })}
            >
                <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange enableColorScheme themes={['light', 'dark']}>
                    <AuthContextProvider>
                        <div className='w-full z-0'>{children}</div>
                    </AuthContextProvider>
                    <Toaster duration={2000} />
                </ThemeProvider>
            </body>
        </html>
    );
}
