import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { AuthContextProvider } from "@/contexts/auth.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head />
            <body
                className={cn(
                    "min-h-screen w-full bg-[#f3f3f3]",
                    inter.className,
                    {
                        "debug-screens": process.env.NODE_ENV === "development",
                    }
                )}
            >
                <AuthContextProvider>
                    <div className="w-full">{children}</div>
                </AuthContextProvider>
                <Toaster />
            </body>
        </html>
    );
}
