import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { AuthContextProvider } from "@/contexts/auth.context";
import { ThemeProvider } from "@/provider/theme-provider";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-dm-sans",
});
export const metadata: Metadata = {
    title: "TaleNet",
    description: "Generated by create next app",
    applicationName: "TaleNet",
    generator: "Next.js",
    keywords: ["TaleNet", "Book", "Network", "Read Book", "Write Book", "Story", "Love Book"],
    creator: "Phan Kien",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html className={`light ${dmSans.variable}`} suppressHydrationWarning>
            <head />
            <body>
                <ThemeProvider attribute='class' defaultTheme='light' enableSystem disableTransitionOnChange enableColorScheme themes={["light", "dark"]}>
                    <AuthContextProvider>{children}</AuthContextProvider>
                    <Toaster duration={2000} />
                </ThemeProvider>
            </body>
        </html>
    );
}
